# Generated by Django 3.2.5 on 2021-07-15 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Civilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colum', models.IntegerField()),
                ('row', models.IntegerField()),
                ('controler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiles', to='controlpanel.civilization')),
            ],
        ),
    ]
