# Generated by Django 3.2.5 on 2021-07-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='desert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tile',
            name='forest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tile',
            name='hills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tile',
            name='lake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tile',
            name='mountain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tile',
            name='plains',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tile',
            name='river',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tile',
            name='shore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tile',
            name='snowy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tile',
            name='tropical_forest',
            field=models.BooleanField(default=False),
        ),
    ]
