# Generated by Django 3.2.5 on 2021-07-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlpanel", "0003_settlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlement",
            name="is_capital",
            field=models.BooleanField(default=False),
        ),
    ]
