# Generated by Django 3.2.5 on 2021-07-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlpanel", "0004_settlement_is_capital"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tile",
            old_name="colum",
            new_name="x",
        ),
        migrations.RenameField(
            model_name="tile",
            old_name="row",
            new_name="y",
        ),
        migrations.AddField(
            model_name="tile",
            name="z",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
