# Generated by Django 3.2.5 on 2021-07-20 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0008_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='building',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='controlpanel.settlement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='civilization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='controlpanel.civilization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='needed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tecnology',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='territory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='controlpanel.tile'),
        ),
    ]
