# Generated by Django 3.2.5 on 2021-07-23 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("controlpanel", "0010_tile_maintance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tile",
            name="controler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tiles",
                to="controlpanel.civilization",
            ),
        ),
    ]
