# Generated by Django 3.2.5 on 2021-07-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0012_civtec_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilization',
            name='technologies',
            field=models.ManyToManyField(through='controlpanel.CivTec', to='controlpanel.Technology'),
        ),
    ]
