# Generated by Django 3.2.5 on 2021-07-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlpanel", "0017_technology_prerequisite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="civtec",
            name="needed_maintance",
        ),
        migrations.AddField(
            model_name="technology",
            name="needed_maintance",
            field=models.IntegerField(null=True),
        ),
    ]
