# Generated by Django 3.2.5 on 2021-07-28 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controlpanel', '0015_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spent', models.IntegerField(default=0)),
                ('last_spent', models.FloatField()),
                ('needed', models.IntegerField(blank=True, default=None, null=True)),
                ('civilization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='controlpanel.civilization')),
            ],
        ),
        migrations.CreateModel(
            name='TileMaintanceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintaned', models.BooleanField(default=False)),
                ('base_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('tile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintance_project', to='controlpanel.tile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnologyMaintanceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintaned', models.BooleanField(default=False)),
                ('base_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('technology', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintance_project', to='controlpanel.technology')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SettlementProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('setlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='controlpanel.settlement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_type', models.CharField(max_length=100)),
                ('base_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExplorationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='controlpanel.tile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
