# Generated by Django 3.2.5 on 2021-07-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_auto_20210729_1742"),
    ]

    operations = [
        migrations.RenameField(
            model_name="settlementproject",
            old_name="setlement",
            new_name="settlement",
        ),
    ]
