# Generated by Django 3.2.5 on 2021-07-23 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controlpanel', '0013_civilization_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentDisaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('civilization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlpanel.civilization')),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disasters.disaster')),
            ],
        ),
    ]
