# Asset Names
# Todo...?
FOREST_NAME = "Forest"
TROPICAL_FOREST_NAME = "Tropical Forest"
RIVER_NAME = "River"
SHORE_NAME = "Shore"
PLAINS_NAME = "Plains"
HILL_NAME = "Hill"
SWAMP_NAME = "Swamp"

MOUNTAIN_NAME = "Mountain"
OCEAN_NAME = "Ocean"
CANYON_NAME = "Canyon"
CLIFF_NAME = "Cliff"
LAKE_NAME = "Lake"
DESERT_NAME = "Desert"
COLD_NAME = "Cold"

ALL_ASSETS = [
    FOREST_NAME,
    TROPICAL_FOREST_NAME,
    RIVER_NAME,
    SHORE_NAME,
    PLAINS_NAME,
    HILL_NAME,
    SWAMP_NAME,
    MOUNTAIN_NAME,
    OCEAN_NAME,
    CANYON_NAME,
    LAKE_NAME,
    CLIFF_NAME,
    DESERT_NAME,
    COLD_NAME,
]
